services:
  db:
    container_name: mysql
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD:-pa55w0rd}
      - MYSQL_DATABASE=${DB_NAME:-test}
      - MYSQL_USER=${DB_USER:-user}
      - MYSQL_PASSWORD=${DB_PASSWORD:-pass}
    ports:
      - ${DB_PORT:-3306}:3306
    volumes:
      - type: volume
        source: db-data
        target: /var/lib/mysql

volumes:
  db-data:
